# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eddbf1ea21e8859250f00eafae3eff7917ba196cdef0125228eb9951edc5ea69b97d2c989ea2a2c59ad6e5a6523be698da20b66f64ed2a52a7e9a1a0dd6cc696

test:
  secret_key_base: de8f19995dd6fd4523b89735d55be338cf4d5d8a47ac0d4d3ebd490418ba685d40f72285ae81593b5fc580521e26a8c84a902098d349aa13e9dd71e3433ba189

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
